version: '3.8'

services:
  oracle-db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: global-solution-oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: ${DB_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - global-solution-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: global-solution-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - oracle-db
    networks:
      - global-solution-net

volumes:
  oracle_data:

networks:
  global-solution-net:
    driver: bridge
